;; "brute force" algorithm O(n^3)

(define (maxsegsum1 A)
  (let ((L (vector-length A))
        (imax 0)
        (jmax 0)
        (Vmax (vector-ref A 0)))
    (do ((i 0 (+ i 1)))
        ((= i L)
         (vector imax jmax Vmax))
      (do ((j i (+ j 1)))
          ((= j L))
        (let ((V 0))
          (do ((k i (+ k 1)))
              ((> k j)
               (if (> V Vmax)
                   (begin
                     (set! Vmax V)
                     (set! imax i)
                     (set! jmax j))))
            (set! V (+ V (vector-ref A k)))))))))


;; cumulative sum pre computation algorithm O(n^2)

(define (maxsegsum2 A)
  (let* ((L (vector-length A))
         (B (make-vector (+ L 1) 0)))
    (do ((i 0 (+ i 1)))
        ((= i L))
      (vector-set! B (+ i 1) (+ (vector-ref B i) (vector-ref A i))))
  (let ((imax 0)
        (jmax 0)
        (Vmax (vector-ref B 1)))
    (do ((i 0 (+ i 1)))
        ((= i L)
         (vector imax jmax Vmax L))
      (do ((j i (+ j 1)))
          ((= j L))
        (let ((V (- (vector-ref B (+ j 1)) (vector-ref B i))))
          (if (> V Vmax)
              (begin
                (set! Vmax V)
                (set! imax i)
                (set! jmax j)))))))))
